--
-- PostgreSQL database dump
--

\restrict vhRIMmEUTgF8T79ayJqE2v048h8lpMFILaU2KnVJ9abipFkU8qbfsbemysRuKk0

-- Dumped from database version 15.18 (Postgres.app)
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-09 23:20:46 CDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16746)
-- Name: Category; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."Category" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "DateAdded" timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone NOT NULL
);


ALTER TABLE public."Category" OWNER TO testtaylor;

--
-- TOC entry 215 (class 1259 OID 16745)
-- Name: Category_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."Category" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16824)
-- Name: Refunds; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."Refunds" (
    "Id" integer NOT NULL,
    "TransactionId" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "Description" text NOT NULL,
    "RefundDate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "DateAdded" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "Status" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Refunds" OWNER TO testtaylor;

--
-- TOC entry 221 (class 1259 OID 16823)
-- Name: Refunds_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."Refunds" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Refunds_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16754)
-- Name: Source; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."Source" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "DateAdded" timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone NOT NULL
);


ALTER TABLE public."Source" OWNER TO testtaylor;

--
-- TOC entry 217 (class 1259 OID 16753)
-- Name: Source_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."Source" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Source_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16839)
-- Name: Tags; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."Tags" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "DateAdded" timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone NOT NULL
);


ALTER TABLE public."Tags" OWNER TO testtaylor;

--
-- TOC entry 223 (class 1259 OID 16838)
-- Name: Tags_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."Tags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16804)
-- Name: Transaction; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."Transaction" (
    "Id" integer NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "SourceId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "DateAdded" timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone NOT NULL
);


ALTER TABLE public."Transaction" OWNER TO testtaylor;

--
-- TOC entry 225 (class 1259 OID 16846)
-- Name: TransactionTags; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."TransactionTags" (
    "TransactionId" integer NOT NULL,
    "TagId" integer NOT NULL,
    "Id" integer NOT NULL,
    "Status" integer NOT NULL,
    "DateAdded" timestamp with time zone NOT NULL,
    "DateUpdated" timestamp with time zone NOT NULL
);


ALTER TABLE public."TransactionTags" OWNER TO testtaylor;

--
-- TOC entry 226 (class 1259 OID 16863)
-- Name: TransactionTags_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."TransactionTags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TransactionTags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16803)
-- Name: Transaction_Id_seq; Type: SEQUENCE; Schema: public; Owner: testtaylor
--

ALTER TABLE public."Transaction" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transaction_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16740)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: testtaylor
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO testtaylor;

--
-- TOC entry 3498 (class 2606 OID 16752)
-- Name: Category PK_Category; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "PK_Category" PRIMARY KEY ("Id");


--
-- TOC entry 3508 (class 2606 OID 16830)
-- Name: Refunds PK_Refunds; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Refunds"
    ADD CONSTRAINT "PK_Refunds" PRIMARY KEY ("Id");


--
-- TOC entry 3501 (class 2606 OID 16760)
-- Name: Source PK_Source; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Source"
    ADD CONSTRAINT "PK_Source" PRIMARY KEY ("Id");


--
-- TOC entry 3510 (class 2606 OID 16845)
-- Name: Tags PK_Tags; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "PK_Tags" PRIMARY KEY ("Id");


--
-- TOC entry 3505 (class 2606 OID 16810)
-- Name: Transaction PK_Transaction; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id");


--
-- TOC entry 3513 (class 2606 OID 16850)
-- Name: TransactionTags PK_TransactionTags; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."TransactionTags"
    ADD CONSTRAINT "PK_TransactionTags" PRIMARY KEY ("TransactionId", "TagId");


--
-- TOC entry 3495 (class 2606 OID 16744)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3496 (class 1259 OID 16802)
-- Name: IX_Category_Name; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE UNIQUE INDEX "IX_Category_Name" ON public."Category" USING btree ("Name");


--
-- TOC entry 3506 (class 1259 OID 16836)
-- Name: IX_Refunds_TransactionId; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE INDEX "IX_Refunds_TransactionId" ON public."Refunds" USING btree ("TransactionId");


--
-- TOC entry 3499 (class 1259 OID 16801)
-- Name: IX_Source_Name; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE UNIQUE INDEX "IX_Source_Name" ON public."Source" USING btree ("Name");


--
-- TOC entry 3511 (class 1259 OID 16861)
-- Name: IX_TransactionTags_TagId; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE INDEX "IX_TransactionTags_TagId" ON public."TransactionTags" USING btree ("TagId");


--
-- TOC entry 3502 (class 1259 OID 16821)
-- Name: IX_Transaction_CategoryId; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE INDEX "IX_Transaction_CategoryId" ON public."Transaction" USING btree ("CategoryId");


--
-- TOC entry 3503 (class 1259 OID 16822)
-- Name: IX_Transaction_SourceId; Type: INDEX; Schema: public; Owner: testtaylor
--

CREATE INDEX "IX_Transaction_SourceId" ON public."Transaction" USING btree ("SourceId");


--
-- TOC entry 3516 (class 2606 OID 16831)
-- Name: Refunds FK_Refunds_Transaction_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Refunds"
    ADD CONSTRAINT "FK_Refunds_Transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES public."Transaction"("Id") ON DELETE CASCADE;


--
-- TOC entry 3517 (class 2606 OID 16851)
-- Name: TransactionTags FK_TransactionTags_Tags_TagId; Type: FK CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."TransactionTags"
    ADD CONSTRAINT "FK_TransactionTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES public."Tags"("Id") ON DELETE CASCADE;


--
-- TOC entry 3518 (class 2606 OID 16856)
-- Name: TransactionTags FK_TransactionTags_Transaction_TransactionId; Type: FK CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."TransactionTags"
    ADD CONSTRAINT "FK_TransactionTags_Transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES public."Transaction"("Id") ON DELETE CASCADE;


--
-- TOC entry 3514 (class 2606 OID 16811)
-- Name: Transaction FK_Transaction_Category; Type: FK CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Category" FOREIGN KEY ("CategoryId") REFERENCES public."Category"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3515 (class 2606 OID 16816)
-- Name: Transaction FK_Transaction_Source; Type: FK CONSTRAINT; Schema: public; Owner: testtaylor
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Source" FOREIGN KEY ("SourceId") REFERENCES public."Source"("Id") ON DELETE RESTRICT;


-- Completed on 2026-07-09 23:20:46 CDT

--
-- PostgreSQL database dump complete
--

\unrestrict vhRIMmEUTgF8T79ayJqE2v048h8lpMFILaU2KnVJ9abipFkU8qbfsbemysRuKk0

